inherit_from: .rubocop_todo.yml
# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

AllCops:
  Exclude:
    - spec/**/*
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - db/migrate/*
    - vendor/**/*
  Rails:
    enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false